### ISSUE TITLE
i cant compile a project 

### ISSUE THREAD

**Issue by leecloudvictor** [vitasdk/vdpm#10]
$ cmake ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/local/vitasdk/bin/arm-vita-eabi-gcc
-- Check for working C compiler: /usr/local/vitasdk/bin/arm-vita-eabi-gcc -- broken
CMake Error at /usr/share/cmake-3.6.2/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/local/vitasdk/bin/arm-vita-eabi-gcc" is not able to
  compile a simple test program.

  It fails with the following output:

   Change Dir: /home/KING/psvproj/VitaShell/build/CMakeFiles/CMakeTmp

  Run Build Command:"/usr/bin/make.exe" "cmTC_540af/fast"

  /usr/bin/make -f CMakeFiles/cmTC_540af.dir/build.make
  CMakeFiles/cmTC_540af.dir/build

  make[1]:
  进入目录“/home/KING/psvproj/VitaShell/build/CMakeFiles/CMakeTmp”

  Building C object CMakeFiles/cmTC_540af.dir/testCCompiler.c.obj

  /usr/local/vitasdk/bin/arm-vita-eabi-gcc -Wl,-q -o
  CMakeFiles/cmTC_540af.dir/testCCompiler.c.obj -c
  /home/KING/psvproj/VitaShell/build/CMakeFiles/CMakeTmp/testCCompiler.c

  make[1]: ***
  [CMakeFiles/cmTC_540af.dir/build.make:66：CMakeFiles/cmTC_540af.dir/testCCompiler.c.obj]
  错误 127

  make[1]:
  离开目录“/home/KING/psvproj/VitaShell/build/CMakeFiles/CMakeTmp”

  make: *** [Makefile:126：cmTC_540af/fast] 错误 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:13 (project)

-- Configuring incomplete, errors occurred!
See also "/home/KING/psvproj/VitaShell/build/CMakeFiles/CMakeOutput.log".
See also "/home/KING/psvproj/VitaShell/build/CMakeFiles/CMakeError.log".

**Comment by devnoname120** [comment]
Could you try to reinstall the vitasdk and set the environment variables as asked by vdpm when it closes?

**Comment by leecloudvictor** [comment]
Yes i do it again and again, But still have problem "arm-vita-eabi-gcc" cloud not use 
my environment is windows 7+Msys2 x68_64

**Comment by limyz** [comment]
Make sure you are running mingw64 not msys2. Refer to https://www.reddit.com/r/vitahacks/comments/60f0ae/help_compiling_hello_world/

**Comment by AlexChecker** [comment]
I have same issue, but on MacOS 10.13. Exactly same error about arm-vita-eabi-gcc. I've updated it just moment ago
