### ISSUE TITLE
Problem w/ SceKernelDmacmgr_stub

### ISSUE THREAD

**Issue by godreborn** [vitasdk/vdpm#105]
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.3.0/../../../../arm-vita-eabi/bin/ld: cannot find -lSceKernelDmacmgr_stub
collect2: error: ld returned 1 exit status
make: *** [Makefile:44: smworld.elf] Error 1

I keep getting this error when compiling projects that use this stub.  I tried vdpm SceKernelDmacmgr, but it says it's already installed.  if I try to force a reinstall, this happens:

![image](https://github.com/vitasdk/vdpm/assets/13548481/75e6b86c-057d-457b-bcea-7da43912bd12)

I'm not really sure what's happening.

**Comment by Rinnegatamante** [comment]
Linux is case sensitive, it's SceKernelDmacMgr.

**Comment by godreborn** [comment]
thanks.  I changed it to that, still same error.  I tried on msys as well, and this gave me a little more information.  it says that it doesn't exist.  I have the stub, but it's not being detected.  I even went as far as reinstalling the sdk, and still nothing.

**Comment by Rinnegatamante** [comment]
The library is part of vitasdk, it's not something shipped via vdpm.
![immagine](https://github.com/vitasdk/vdpm/assets/9152710/62a5af83-015b-445e-963f-503a8396fce6)

**Comment by godreborn** [comment]
I have them: 
![image](https://github.com/vitasdk/vdpm/assets/13548481/075f3fe0-ee93-4b65-8d1a-59c55adc74b8)

however, when I attempted to compile your super mario world, it said it couldn't find it.  it's the only error I got.

**Comment by godreborn** [comment]
nm, I got it: 
![image](https://github.com/vitasdk/vdpm/assets/13548481/aad07caa-b21f-4972-8d0a-b035404e849a)

I changed the case sensitive name in the Makefile.
