### ISSUE TITLE
Bootstrap Install fail on Antergos

### ISSUE THREAD

**Issue by yne** [vitasdk/vdpm#21]
The following line fail on Antergos (and possibly on any arch based distrib) 
https://github.com/vitasdk/vdpm/blob/be741192638e0283197af397cf773d7fe139d923/bootstrap-vitasdk.sh#L27

Because my groupname (`users`) is not my name (`yne`)

A simple fix would be to use `$USER:$(id -gn $USER)` instead

**Comment by devnoname120** [comment]
Feel free to do a pull request.

**Comment by yne** [comment]
Okay,
Let's hope It will not break stuff for another distro.
