### ISSUE TITLE
$VITASDK is not set

### ISSUE THREAD

**Issue by paulomatosx** [vitasdk/vdpm#29]
when I type "./install-all.sh" it return -> $VITASDK is not set

How can I set it?

I was trying with: 
export VITASDK=/usr/local/vitasdk
and
export PATH=$VITASDK/bin:$PATH
![sem titulo](https://user-images.githubusercontent.com/33873743/36073592-6fdec74a-0f1a-11e8-85c9-7069f446033a.png)

**Comment by xerpi** [comment]
I think the commands run by sudo don't have the same environment variables. Try `sudo echo $VITASDK`.

**Comment by paulomatosx** [comment]
Thanks xerpi!
sudo echo, not worked, but you were right, I got sucess with root how default.
Thank you very much!

**Comment by javo92** [comment]
In case someone runs into this issue, I solved it (without changing to the root user) using the option -E with sudo: 
sudo -E ./install-all.sh

**Comment by CelesteBlue-dev** [comment]
Have you wrote the command in .bashrc ?

**Comment by yne** [comment]
@CelesteBlue-dev as you can see on the screencap he wrote them on the shell prompt, but writing them on the .bashrc would give the same outcome.
as @javo92 suggest the workaround is to use the `-E` flag to forward the user's env while sudo-ing
from `man sudo`
```
     -E, --preserve-env
                 Indicates to the security policy that the user wishes to pre‐
                 serve their existing environment variables.  The security
                 policy may return an error if the user does not have permis‐
                 sion to preserve the environment.
```

Also maybe we could give a hint while failing about the missing variable.
Something like:
```bash
if [ $EUID -eq 0 -a -z "$VITASDK" ] ; then
  echo 'You seem to be running as root, however your $VITASDK is unset';
  echo "Try to start this script using `sudo -E $0` ";
fi
```

**Comment by kaelyavel** [comment]
> In case someone runs into this issue, I solved it (without changing to the root user) using the option -E with sudo:
> sudo -E ./install-all.sh

This answer solved it for me.

Thank you very much for sharing it.

**Comment by landsman** [comment]
> In case someone runs into this issue, I solved it (without changing to the root user) using the option -E with sudo: sudo -E ./install-all.sh

This helped me as well. It should be in the doc.

**Comment by isage** [comment]
> > In case someone runs into this issue, I solved it (without changing to the root user) using the option -E with sudo: sudo -E ./install-all.sh
> 
> This helped me as well. It should be in the doc.

No, it shouldn't.
Does the doc tell you to run stuff with sudo? No. And you shouldn't.

**Comment by landsman** [comment]
I ment that -E parameter

**Comment by isage** [comment]
> I ment that -E parameter

That's the parameter **for sudo**. **don't use sudo**
