### ISSUE TITLE
Unknown hostname in cURL run on OS X

### ISSUE THREAD

**Issue by IngwiePhoenix** [vitasdk/vdpm#39]
Appearently, the shell method to get the proper download URL does not work as expected :)

```
Ingwie@Ingwies-Macbook-Pro.local ~/W/G/vdpm $ sudo bash -x ./bootstrap-vitasdk.sh 
+ set -e
+++ dirname ./bootstrap-vitasdk.sh
++ cd .
++ pwd
+ DIR=/Users/Ingwie/Work/Git/vdpm
+ INSTALLDIR=/usr/local/vitasdk
+ . /Users/Ingwie/Work/Git/vdpm/include/install-vitasdk.sh
+ '[' -d /usr/local/vitasdk ']'
+ echo '==> Installing vitasdk to /usr/local/vitasdk'
==> Installing vitasdk to /usr/local/vitasdk
+ install_vitasdk /usr/local/vitasdk
+ INSTALLDIR=/usr/local/vitasdk
+ case "$(uname -s)" in
++ uname -s
+ mkdir -p /usr/local/vitasdk
++ get_download_link osx
++ curl https://api.github.com/repos/vitasdk/autobuilds/releases
++ grep master
++ grep browser_download_url
++ grep osx
++ head -n 1
++ cut -d '"' -f 4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  115k  100  115k    0     0   127k      0 --:--:-- --:--:-- --:--:--  127k
+ wget -O vitasdk-nightly.tar.bz2 ''
http://: Ungültiger Hostname.
```
("Ungültiger Hostname" -> "Invalid hostname")

Maybe you could patch this? I have a Vita and VitaTV and would like to fool around with them! :)

**Comment by plato79** [comment]
It seems autobuilds are stopped for osx hosts.. I checked, there are builds for windows and linux but not osx.

**Comment by IngwiePhoenix** [comment]
All I can offer is to zip up my `/usr/local/vitasdk` and upload it.

**Comment by franciscomfcmaia** [comment]
You could forcefully download the latest OSX build by changing the install script (install-vitasdk.sh) like so:
[install-vitasdk.txt](https://github.com/vitasdk/vdpm/files/2755137/install-vitasdk.txt)
I uploaded a txt file for a quick patch :)

**Comment by ttomato** [comment]
The codes in script include/install-vitasdk.sh  can't work.
`get_download_link () {
  curl "https://api.github.com/repos/vitasdk/autobuilds/releases" | grep "master" | grep "browser_download_url" | grep $1 | head -n 1 | cut -d '"' -f 4
}`

Run 'curl "https://api.github.com/repos/vitasdk/autobuilds/releases' and get the message:
{
  "message": "API rate limit exceeded for 203.100.54.194. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}

And the latest version for Win and Linux is v993 and for osx it's v892......

**Comment by d3m3vilurr** [comment]
last build will work.
