### ISSUE TITLE
Error 2

### ISSUE THREAD

**Issue by munew** [vitasdk/vdpm#42]
Log : 
$ cmake ../
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/local/vitasdk/bin/arm-vita-eabi-gcc
-- Check for working C compiler: /usr/local/vitasdk/bin/arm-vita-eabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/vitasdk/bin/arm-vita-eabi-g++
-- Check for working CXX compiler: /usr/local/vitasdk/bin/arm-vita-eabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for ctype.h
-- Looking for ctype.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Configuring done
CMake Error at CMakeLists.txt:40 (add_executable):
  Cannot find source file:

    substitute/lib/hook-functions.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: taihen
CMake Error: Cannot determine link language for target "taihen".
-- Generating done
-- Build files have been written to: /c/Users/Wykt/Desktop/Project/taiHEN-master/build

$ make
Scanning dependencies of target taihenparser
[ 14%] Building C object taihen-parser/src/CMakeFiles/taihenparser.dir/lexer.c.obj
[ 28%] Building C object taihen-parser/src/CMakeFiles/taihenparser.dir/parser.c.obj
[ 42%] Linking C static library libtaihenparser.a
[ 42%] Built target taihenparser
Scanning dependencies of target taihen
make[2]: *** Aucune règle pour fabriquer la cible « CMakeFiles/taihen.dir/build ». Arrêt.
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/taihen.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

I use mingw64
Sorry, im a noob xd

**Comment by nobodywasishere** [comment]
What was the solution?
