### ISSUE TITLE
Line 4 and Line 21 curl command not found

### ISSUE THREAD

**Issue by seewood** [vitasdk/vdpm#51]
Hey Guys,
i'm trying to install the vitasdk but cannot succeed.
i made the steps from the installation tutorial on linux (ubuntu) but everytime when i want to install the toolchain it ends up with the curl command not found line 4 at ./bootstrap-vitasdk.sh and at ./install-all.sh it is the line 21
Followed this Guide:
https://vitasdk.org/

i made some screenshots for you Guys... can you guide me to success and tell me what i'm doing wrong?
![Bildschirmfoto vom 2020-01-18 20-34-12](https://user-images.githubusercontent.com/33197691/72669549-5f030d00-3a33-11ea-8c6a-7970b5061b16.png)
![Bildschirmfoto vom 2020-01-18 20-36-13](https://user-images.githubusercontent.com/33197691/72669552-61656700-3a33-11ea-95d4-1a2ab8ad400d.png)
![Bildschirmfoto vom 2020-01-18 20-37-16](https://user-images.githubusercontent.com/33197691/72669553-62969400-3a33-11ea-970f-b31c84e4da2a.png)

EDIT:
tried with sudo -E but the same error
![Bildschirmfoto vom 2020-01-18 20-50-39](https://user-images.githubusercontent.com/33197691/72669615-61b23200-3a34-11ea-909c-a1506bf54866.png)

**Comment by yne** [comment]
Try
```
sudo apt install curl
```
then retry

**Comment by seewood** [comment]
Thanks in advance! Missed that curl must be installed! Now its working with:
sudo -E ./install-all.sh

Thank you
