### ISSUE TITLE
Failing on hostname [Linux]

### ISSUE THREAD

**Issue by boazvdwansem** [vitasdk/vdpm#58]
vdpm$ ./bootstrap-vitasdk.sh
==> Installing vitasdk to /usr/local/vitasdk
/usr/bin/curl
/home/username/vdpm/include/install-vitasdk.sh: line 4: python: command not found
http://: Invalid host name.

Host seems to be down...

**Comment by boazvdwansem** [comment]
Edit: It's still happening

**Comment by yne** [comment]
The reason behind seems to be a missing python on your machine

Please install it first and retry.

Maybe we shall print a warning if python is not installed ? or maybe convert the .py to a .sh script so we won't have to rely on 3rd party interpreter

**Comment by boazvdwansem** [comment]
I already had python 3 installed, it seems to work on python 2 only. Anyways I can install bootstrap-vitasdk.sh now. install-all.sh still returns an error, I'll open a new issue.
