### ISSUE TITLE
./install-all.sh fileformat error

### ISSUE THREAD

**Issue by boazvdwansem** [vitasdk/vdpm#61]
share/doc/lame/html/cbr.html
success
Installing fmmpeg...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0   1862      0 --:--:-- --:--:-- --:--:--  1840
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Failed to install, the package probably does not exist.

**Comment by Rinnegatamante** [comment]
https://github.com/vitasdk/vdpm/pull/59
