### ISSUE TITLE
pkg-config files prefix

### ISSUE THREAD

**Issue by isage** [vitasdk/vdpm#69]
Currently, there's a bug in `.pc` files provided by packages in that, that their `prefix` line points to vitasdk path on build machine, which is not always true for end-users, and one of such examples are vitasdk docker image.

One of proposals was to create additional step in `vdpm` to automagically replace prefix line to path pointed by `$VITASDK` in package `.pc` files after installation.

**Comment by glebm** [comment]
Something like this in the right place should do the trick:

```bash
find "${INSTALLDIR}/arm-vita-eabi/lib/pkgconfig/" -name '*.pc' -exec \
  sed -i "s|/usr/local/vitasdk|${INSTALLDIR}|" '{}' \;
```
