### ISSUE TITLE
Please add lib ffmpeg.

### ISSUE THREAD

**Issue by DavisDev** [vitasdk/vdpm#8]

**Comment by devnoname120** [comment]
Keep in kind that this won't be HW-accelerated so it should be slow.

If you are looking for HW-acceleration, then you might want to take a look at [SceVideoDec](http://docs.vitasdk.org/group__SceVideoDecUser.html).
Here is some example of usage: https://github.com/xyzz/vita-moonlight/blob/vita/src/video/vita.c

**Comment by DavisDev** [comment]
I was not aware that someone was already using those functions,
thank you very much!,
I'll give you a view.

**Comment by d3m3vilurr** [comment]
actually sometimes you can't refer vita-moonlight code, because they use gpl. please check just videodec header.

**Comment by limyz** [comment]
As requested on https://github.com/TheOfficialFloW/VitaShell/issues/218. Suggest to close issue if not implementable.

**Comment by devnoname120** [comment]
If someone ports it, then please create a pull request. (FFmpeg should run fast enough to decode audio on the Vita.)
