### ISSUE TITLE
./install-all.sh file format error

### ISSUE THREAD

**Issue by degradka** [vitasdk/vdpm#91]
All the packages installed successfully except the libbaremetal
![image](https://user-images.githubusercontent.com/69397649/198569267-08dcdd7b-cd5d-4d70-a2c5-ed01177cc454.png)

**Comment by isage** [comment]
wait a few hours and re-try

**Comment by degradka** [comment]
> wait a few hours and re-try

Thanks, worked :thumbsup:

**Comment by MiltosKoutsokeras** [comment]
The package [Box2D](https://github.com/vitasdk/vdpm/blob/84c3914a553ccffdaf881bad34ddd704de7041c0/include/install-packages.sh#L67) is also not available [here](https://github.com/vitasdk/packages/releases)
